/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistemapedidos;

import Logic.Pedido;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.ButtonModel;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author jab29
 */
public class Nuevopedido extends javax.swing.JFrame {

    /**
     * Creates new form Nuevopedido
     */
    Confirmarpedido conf = new Confirmarpedido();
    public Nuevopedido() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupdistribuidor = new javax.swing.ButtonGroup();
        lbltitle = new javax.swing.JLabel();
        lblnombre = new javax.swing.JLabel();
        lbltipo = new javax.swing.JLabel();
        lblcantidad = new javax.swing.JLabel();
        lblnombrefarmaceutico = new javax.swing.JLabel();
        lblfarmciadestino = new javax.swing.JLabel();
        txtNombreMedicamento = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        ComboTipo = new javax.swing.JComboBox<>();
        jRbtnCofarma = new javax.swing.JRadioButton();
        jCheckFarmaciaPrincipal = new javax.swing.JCheckBox();
        btnBorrar = new javax.swing.JButton();
        btnConfirmar = new javax.swing.JButton();
        jRbtnEmpsephar = new javax.swing.JRadioButton();
        jRbtnCemefar = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nuevo pedido");

        lbltitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbltitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltitle.setText("Sistema de pedidos de medicamentos");

        lblnombre.setText("Nombre del Medicamento:");

        lbltipo.setText("Tipo del Medicamento:");

        lblcantidad.setText("La cantidad de producto que se requiere:");

        lblnombrefarmaceutico.setText("El nombre del distribuidor farmacéutico:");

        lblfarmciadestino.setText("La sucursal de la farmacia a la cual debe llegar el pedido:");

        ComboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Analgésico", "Analéptico", "Anestésico", "Antiácido", "Antidepresivo", "Antibióticos" }));
        ComboTipo.setFocusCycleRoot(true);

        buttonGroupdistribuidor.add(jRbtnCofarma);
        jRbtnCofarma.setText("Cofarma");

        jCheckFarmaciaPrincipal.setText("Principal");

        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        btnConfirmar.setText("Confirmar");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        buttonGroupdistribuidor.add(jRbtnEmpsephar);
        jRbtnEmpsephar.setText("Empsephar ");

        buttonGroupdistribuidor.add(jRbtnCemefar);
        jRbtnCemefar.setText("Cemefar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblcantidad)
                    .addComponent(lbltitle, javax.swing.GroupLayout.PREFERRED_SIZE, 683, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblnombre)
                            .addComponent(lbltipo)
                            .addComponent(lblnombrefarmaceutico)
                            .addComponent(lblfarmciadestino))
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jCheckFarmaciaPrincipal)
                                .addComponent(ComboTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCantidad)
                                .addComponent(txtNombreMedicamento, javax.swing.GroupLayout.Alignment.CENTER))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRbtnCofarma)
                                .addGap(18, 18, 18)
                                .addComponent(jRbtnEmpsephar)
                                .addGap(18, 18, 18)
                                .addComponent(jRbtnCemefar)))
                        .addGap(40, 40, 40)))
                .addGap(40, 40, 40))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBorrar)
                .addGap(129, 129, 129)
                .addComponent(btnConfirmar)
                .addGap(212, 212, 212))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbltitle, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnombre)
                    .addComponent(txtNombreMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltipo)
                    .addComponent(ComboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcantidad)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnombrefarmaceutico)
                    .addComponent(jRbtnCofarma)
                    .addComponent(jRbtnEmpsephar)
                    .addComponent(jRbtnCemefar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblfarmciadestino)
                    .addComponent(jCheckFarmaciaPrincipal))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBorrar)
                    .addComponent(btnConfirmar))
                .addContainerGap(110, Short.MAX_VALUE))
        );

        ComboTipo.getAccessibleContext().setAccessibleName("");
        ComboTipo.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        // TODO add your handling code here:
        this.txtNombreMedicamento.setText("");
        this.ComboTipo.setSelectedItem("Seleccione");
        this.txtCantidad.setText("");//Javier.diaz@unir.net
        this.jRbtnCemefar.setSelected(false);
        this.jRbtnCofarma.setSelected(false);
        this.jRbtnEmpsephar.setSelected(false);
        this.buttonGroupdistribuidor.clearSelection();
        this.jCheckFarmaciaPrincipal.setSelected(false);
        
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        // TODO add your handling code here:
        try {
            String nombremedicamento = this.txtNombreMedicamento.getText();
            if (nombremedicamento.equals("")) {
                //this.txtNombreMedicamento.setBorder(BorderFactory.createDashedBorder(Color.RED));
                this.txtNombreMedicamento.setBackground(Color.PINK);
                this.txtNombreMedicamento.setCaretPosition(0);
                throw new Exception("El campo 'Nombre del Medicamento' no puede estar vacio");
            } else {
                this.txtNombreMedicamento.setBackground(Color.WHITE);
                //this.txtNombreMedicamento.setBorder(null);
            }
            
            
            String tipomedicamento = this.ComboTipo.getSelectedItem().toString();
            if (tipomedicamento.equals("Seleccione")) { 
                throw new Exception("El campo 'Tipo del Medicamento' no es valido, debe seleccionar un tipo de medicamento"); 
            }
            
            
            String cantidadmedicamento = this.txtCantidad.getText();
            int numerocantidad = 0;
            try {
                numerocantidad = Integer.parseInt(cantidadmedicamento);
            } catch (Exception ex) {
                throw new Exception("El campo 'La cantidad de producto que se requiere' no es valido, debe ser un numero");
            }
            if (numerocantidad <= 0) {
                throw new Exception(" La cantidad de producto que se requiere debe ser mayor a 0");
            }
            
            
            String distribuidor = null;
            if (jRbtnCemefar.isSelected() == true) {
                distribuidor = jRbtnCemefar.getText();
            } else if (jRbtnCofarma.isSelected() == true) {
                distribuidor = jRbtnCofarma.getText();
            } else if (jRbtnEmpsephar.isSelected() == true) {
                distribuidor = jRbtnEmpsephar.getText();
            }
            if (distribuidor == null) {
                throw new Exception("Por favor seleccione un distribuidor");
            }
            

            boolean sucursal = this.jCheckFarmaciaPrincipal.isSelected();
            
            conf.Informacion(new Pedido(nombremedicamento, tipomedicamento, numerocantidad, distribuidor, sucursal));
            conf.setVisible(true);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error no controlado", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_btnConfirmarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Nuevopedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Nuevopedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Nuevopedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Nuevopedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Nuevopedido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboTipo;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.ButtonGroup buttonGroupdistribuidor;
    private javax.swing.JCheckBox jCheckFarmaciaPrincipal;
    private javax.swing.JRadioButton jRbtnCemefar;
    private javax.swing.JRadioButton jRbtnCofarma;
    private javax.swing.JRadioButton jRbtnEmpsephar;
    private javax.swing.JLabel lblcantidad;
    private javax.swing.JLabel lblfarmciadestino;
    private javax.swing.JLabel lblnombre;
    private javax.swing.JLabel lblnombrefarmaceutico;
    private javax.swing.JLabel lbltipo;
    private javax.swing.JLabel lbltitle;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtNombreMedicamento;
    // End of variables declaration//GEN-END:variables
}
